version: 2

sources:
    - name: staging
      database: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: streamify_stg
      tables:
        - name: listen_events
        - name: page_view_events
        - name: auth_events
        - name: songs
        - name: state_codes

    - name: staging
      database: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: streamify_prod
      tables:
        - name: dim_artists
        - name: dim_songs
        - name: dim_datetime
        - name: dim_location
        - name: dim_users
        - name: fact_streams
      views:
        - name: wide_streams